version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    image: nextcloud
    restart: always
    ports:
      - 6080:80
    volumes:
      - ./nextcloud:/var/www/html
      - ./apache2:/etc/apache2
      - ./php:/usr/local/etc/php
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - PHP_UPLOAD_LIMIT=8G
      - PHP_MEMORY_LIMIT=8G
    depends_on:
      - db

volumes:
  db:
  nextcloud:

